services:
  scylla-manager:
    image: scylladb/scylla-manager
    networks:
      event-stream:
    volumes:
      - "./scylla/scylla-manager.yaml:/etc/scylla-manager/scylla-manager.yaml"
    depends_on:
      - scylla-db
    ports:
      - "5080:5080"

  scylla-db:
    image: scylladb/scylla
    volumes:
      - scylla-data:/var/lib/scylla
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
    networks:
      event-stream:
    command: --smp 1 --memory 1G
    ports:
      - "9042:9042"

#  scylla-agent:
#    image: scylladb/scylla-with-agent
#    volumes:
#      - "./scylla/scylla-manager-agent.yaml:/etc/scylla-manager/scylla-manager-agent.yaml"
#    networks:
#      event-stream:
#    command: --smp 1


#  minio:
#    image: minio/minio
#    networks:
#      event-stream:
#    ports:
#      - "9001:9000"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: miniominio
#    command: server /data

volumes:
  scylla-data:

networks:
  event-stream:
    driver: bridge