services:
  scylla-manager:
    image: scylladb/scylla-manager
    networks:
      event-stream:
    volumes:
      - "./scylla/scylla-manager.yaml:/etc/scylla-manager/scylla-manager.yaml"
    depends_on:
      - scylla-db
    ports:
      - "5080:5080"

  scylla-db:
    image: scylladb/scylla
    volumes:
      - scylla-data:/var/lib/scylla
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
    networks:
      event-stream:
    command: --smp 1 --memory 1G
    ports:
      - "9042:9042"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      event-stream:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      event-stream:
    environment:
      KAFKA_BROKERS: kafka:29092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: '6000'
      KAFKA_RESTART_ATTEMPTS: '10'
      KAFKA_RESTART_DELAY: '5'
      KAFKA_ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: '0'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 15728640
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_BROKER_ID: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    networks:
      event-stream:
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.3
    restart: unless-stopped
    networks:
      event-stream:
    depends_on:
      - kafka
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


#  scylla-agent:
#    image: scylladb/scylla-with-agent
#    volumes:
#      - "./scylla/scylla-manager-agent.yaml:/etc/scylla-manager/scylla-manager-agent.yaml"
#    networks:
#      event-stream:
#    command: --smp 1


#  minio:
#    image: minio/minio
#    networks:
#      event-stream:
#    ports:
#      - "9001:9000"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: miniominio
#    command: server /data

volumes:
  scylla-data:
  zk_data:
  zk_logs:
  kafka_data:

networks:
  event-stream:
    driver: bridge